# Generated by Django 4.2.3 on 2023-07-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=255, verbose_name='Ad və soyad')),
                ('leqeb', models.CharField(blank=True, default='yoxdur.', max_length=100, verbose_name='Ləqəbi')),
                ('dogum_tarixi', models.DateField(verbose_name='Doğum tarixi')),
                ('vefat_tarixi', models.DateField(verbose_name='Vəfat tarixi')),
                ('dogum_yeri', models.CharField(max_length=255, verbose_name='Doğulduğu yer')),
                ('vefat_yeri', models.CharField(max_length=255, verbose_name='Vəfat yeri')),
                ('vetendasligi', models.CharField(max_length=50, verbose_name='Vətəndaşlığı')),
                ('qosun_novu', models.CharField(max_length=100, verbose_name='Qoşun növü')),
                ('mensubiyyeti', models.CharField(max_length=100, verbose_name='Mənsubiyyəti')),
                ('xidmet_illeri', models.CharField(max_length=100, verbose_name='Xidmət illəri')),
            ],
        ),
        migrations.CreateModel(
            name='Rutbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
