# Generated by Django 4.2.2 on 2023-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ad_soyad',
        ),
        migrations.AddField(
            model_name='person',
            name='ad',
            field=models.CharField(default='', max_length=50, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='person',
            name='ata_adi',
            field=models.CharField(default='', max_length=50, verbose_name='Ata adı'),
        ),
        migrations.AddField(
            model_name='person',
            name='soyad',
            field=models.CharField(default='', max_length=50, verbose_name='Soyadı'),
        ),
    ]
