# Generated by Django 4.2.2 on 2023-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_person_ad_soyad_person_ad_person_ata_adi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QosunNovu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, null=True, verbose_name='Qoşun adı')),
            ],
        ),
        migrations.AddField(
            model_name='rutbe',
            name='ad',
            field=models.CharField(max_length=100, null=True, verbose_name='Rütbə adı'),
        ),
    ]
