# Generated by Django 4.2.2 on 2023-08-01 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_person_qosun_novu'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='medallar',
            field=models.ManyToManyField(to='main.medallar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qosun_novu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qosunnovu', verbose_name='Qoşun növü'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rutbe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rutbe', verbose_name='Rütbə'),
        ),
    ]
