# Generated by Django 4.2.2 on 2023-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_person_cinsiyeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cinsiyeti',
            field=models.CharField(choices=[('Kişi', 'Kişi'), ('Qadın', 'Qadın')], default='Kişi', max_length=5, verbose_name='Cinsiyyəti seçin'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mensubiyyeti',
            field=models.CharField(default='Azərbaycan Ordusu', max_length=100, verbose_name='Mənsubiyyəti'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sekil',
            field=models.ImageField(blank=True, default='static/img/default-man.jpg', null=True, upload_to='main/uploads/%d/%m/%Y', verbose_name='Şəkil'),
        ),
    ]
