# Generated by Django 4.2.2 on 2023-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_person_cinsiyeti_alter_person_mensubiyyeti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rutbe',
        ),
        migrations.AddField(
            model_name='person',
            name='rutbe',
            field=models.ManyToManyField(to='main.rutbe', verbose_name='Rütbə'),
        ),
    ]
