# Generated by Django 4.2.2 on 2023-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_person_rutbe_person_rutbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='haqqinda',
            field=models.TextField(default='Haqqında heç bir məlumat yoxdur', verbose_name='Haqqında'),
        ),
        migrations.AlterField(
            model_name='person',
            name='medallar',
            field=models.ManyToManyField(to='main.medallar', verbose_name='Medallar'),
        ),
    ]
