# Generated by Django 4.2.2 on 2023-08-20 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_person_haqqinda_alter_person_medallar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='haqqinda',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
